CREATE TABLE living_space (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address_type TEXT NOT NULL,
    street_address TEXT NOT NULL,
    apt_number TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    zip_code TEXT NOT NULL,
    Included TEXT,
    comments TEXT,
    monthly_payment TEXT NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);